#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    temp=[]
    name = ""
    list = s.split(" ")
    for word in list:
        temp.append(word.capitalize())
    name = " ".join(temp)
    return name

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
